version: '3'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./miniflux-db:/var/lib/postgresql/data
  miniflux:
    container_name: miniflux
    build: .
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
